### ISSUE TITLE
Setting Up farmOS With DDEV and Composer

### ISSUE THREAD

**Issue by rgcarr** [farmOS/farmOS-community-blog#18]
DDEV is a great way to build Drupal (and other PHP-based) projects in a local environment; when combined with Colima and Mutagen, not only is the requirement for Docker desktop removed, but performance can be impressively fast. Instructions on setting up DDEV are at https://ddev.readthedocs.io/en/latest/users/install/

The recommended method to install a farmOS local development environment (https://farmos.org/development/environment) is via a Docker container, but this may not work well with Colima.

For certain local environments, installing farmOS by Composer may be more straightforward. The following commands would allow farmOS to be installed in a DDEV container:

```
mkdir farmos-ddev
cd farmos-ddev
ddev config --project-type=drupal9 --docroot=web --create-docroot
ddev start
ddev composer create "farmos/project:2.x-dev"
ddev composer require drush/drush
ddev drush site:install --account-name=admin --account-pass=admin -y
ddev drush uli
ddev launch
```
(HT @wotnak)

**Comment by paul121** [comment]
We should make sure that the DDEV instructions include PostgreSQL and PHP-GEOS. I've included an example and some info on this here but I think (especially the PostgreSQL piece) could be improved for latest DDEV versions: https://farmos.discourse.group/t/installing-on-ddev-via-composer/1646/7?u=paul121

**Comment by rgcarr** [comment]
I'm still finding my way around Github... I started a PR at https://github.com/rgcarr/farmOS-community-blog/pull/1 - I've no idea how that gets referenced here on this issue. 

Anyway, @paul121 I agree that we should put a few recipes together for other local dev environments.

**Comment by paul121** [comment]
Oh nice! You made a PR against your own fork. I'm not sure if you can "transfer" that to this farmos/farmos-community-blog repo... but you can make a new PR! If you open that `rgcarr-ddev-farmos-composer-1` branch in the UI [here](https://github.com/rgcarr/farmOS-community-blog/tree/rgcarr-ddev-farmos-composer-1) you should see a "contribute" button at the top to make the PR?

**Comment by rgcarr** [comment]
OK this is fun... unless I'm creating work for someone else. 

I think I've now done a PR against the main branch. Not sure if anyone else can access that and make further updates.

Everyday is a school day

**Comment by paul121** [comment]
Yep this is a great start, thanks @rgcarr ! I'd like to figure out the postgres piece I mentioned since that is the DB we recommend. If it can remove the need for copying my `.ddev` directory that would be great, and it seems like that may be the case. I will try and make progress on that this week

**Comment by wotnak** [comment]
farmOS ddev setup with postgres and php-geos:
```bash
ddev config --project-type=drupal9 --docroot=web --create-docroot --database=postgres:15 --php-version=8.1
ddev get wotnak/ddev-php-geos
ddev start
ddev composer create farmos/project:2.x-dev
ddev drush site:install
```

**Comment by paul121** [comment]
@wotnak that is so great! I think we can turn attention to wrapping up the PR for the blog post :-)

**Comment by RMattB1** [comment]
Hi all, 
I'm trying to install an experimental local instance of the latest farmos release in a ddev environment, and arrived here via: 
- https://farmos.org/development/environment/
- https://farmos.discourse.group/t/installing-on-ddev-via-composer
- PR https://github.com/farmOS/farmOS-community-blog/pull/19

Is [this page's top post](https://github.com/farmOS/farmOS-community-blog/issues/18#issue-1712349563) the final/canonical doc, or did it end up getting refined and published somewhere under here?: 
https://farmos.org/development
Thanks!

Matt

**Comment by mstenta** [comment]
@RMattB1 This repository publishes to https://farmOS.org/blog

Here is the final blog post: https://farmos.org/blog/2023/installing-farmos-on-ddev-with-composer/

Note that we do not maintain blog posts as things change in farmOS, so they may become outdated, but I assume this one is still good.
